# Generated by Django 5.0.3 on 2024-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=7),
        ),
    ]
