# Generated by Django 5.0.3 on 2024-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('bus_id', models.IntegerField()),
                ('status', models.CharField(choices=[('B', 'booked'), ('C', 'cancelled')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('nos', models.IntegerField()),
                ('booked', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
